services:
  mariadb-fila:
    image: mariadb:10.5
    container_name: mariadb-fila
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fila
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fiap-net
  springboot-fila:
    build:
      context: .
    container_name: springboot-fila
    depends_on:
      - mariadb-fila
    ports:
        - "8081:8081"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta para apps
      - "15672:15672"   # Painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - fiap-net

networks:
  fiap-net:
    driver: bridge